apiVersion: v2
name: saleor
description: A Helm chart for Saleor e-commerce platform
type: application
version: 0.1.16
appVersion: "3.20"
dependencies:
  - name: postgresql
    version: ~12.5.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ~17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled