replicaCount: 1

images:
  api: ghcr.io/saleor/saleor:3.20
  dashboard: ghcr.io/saleor/saleor-dashboard:latest
  db: library/postgres:15-alpine
  redis: library/redis:7.0-alpine
  worker: ghcr.io/saleor/saleor:3.20
  jaeger: jaegertracing/all-in-one
  mailpit: axllent/mailpit

services:
  api:
    port: 8000
    type: ClusterIP
  dashboard:
    port: 9000
    type: ClusterIP
  db:
    port: 5432
    type: ClusterIP
  redis:
    port: 6379
    type: ClusterIP
  jaeger:
    ports:
      - 5775
      - 6831
      - 6832
      - 5778
      - 16686
      - 14268
      - 9411
    type: ClusterIP
  mailpit:
    smtpPort: 1025
    webPort: 8025
    type: ClusterIP

env:
  api:
    JAEGER_AGENT_HOST: "jaeger"
    DASHBOARD_URL: "http://localhost:9000/"
    ALLOWED_HOSTS: "localhost,api"
  db:
    POSTGRES_USER: "saleor"
    POSTGRES_PASSWORD: "saleor"

volumes:
  saleorDb: /var/lib/postgresql/data
  saleorRedis: /data
  saleorMedia: /app/media