api:
  replicaCount: 1
  image:
    repository: ghcr.io/saleor/saleor
    tag: "3.20"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  dashboardUrl: "http://localhost:9000/"
  allowedHosts: "localhost,api"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  extraEnv: []

dashboard:
  replicaCount: 1
  image:
    repository: ghcr.io/saleor/saleor-dashboard
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

# Add default service configuration
service:
  type: ClusterIP
  port: 8000

worker:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

storage:
  media:
    size: 10Gi

postgresql:
  enabled: true
  auth:
    username: saleor
    password: saleor
    database: saleor
  primary:
    persistence:
      size: 10Gi

redis:
  enabled: true
  auth:
    password: saleor
  architecture: standalone