# Default values for saleor chart
global:
  database:
    host: db
    port: 5432
    name: saleor
    user: saleor
    password: saleor
  env:
    DEFAULT_CHANNEL_SLUG: default-channel
    HTTP_IP_FILTER_ALLOW_LOOPBACK_IPS: "True"
    HTTP_IP_FILTER_ENABLED: "True"
    CELERY_BROKER_URL: redis://redis:6379/1
    DEFAULT_FROM_EMAIL: noreply@example.com
    EMAIL_URL: smtp://mailpit:1025
    SECRET_KEY: changeme
    JAEGER_AGENT_HOST: jaeger
    DASHBOARD_URL: http://localhost:9000/
    DATABASE_URL: postgres://[username]:[password]@[host]/[database_name]
    ALLOWED_HOSTS: localhost,api
    API_URL: http://localhost:8000/
    STATIC_URL: http://localhost:9000/
    PUBLIC_URL: https://your-domain.com
    ALLOWED_CLIENT_HOSTS: "your-domain.com"
    ENABLE_SSL: "True"

    DEFAULT_FILE_STORAGE: "storages.backends.gcloud.GoogleCloudStorage"
    GS_CREDENTIALS_FILE_PATH: "/etc/secrets/gcs-service-account.json"
    GS_BUCKET_NAME: "name_backet"
    MEDIA_URL: "https://storage.googleapis.com/name-backet/"

api:
  image:
    repository: ghcr.io/saleor/saleor
    tag: "3.20"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources: {}

dashboard:
  image:
    repository: ghcr.io/saleor/saleor-dashboard
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}

worker:
  image:
    repository: ghcr.io/saleor/saleor
    tag: "3.20"
    pullPolicy: IfNotPresent
  resources: {}

storefront:
  enabled: false
  replicas: 2
  image:
    repository: your-docker-repo/saleor-storefront
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: "512Mi"
      cpu: "250m"
    requests:
      memory: "256Mi"
      cpu: "125m"
  env:
    NEXT_PUBLIC_SALEOR_API_URL: "https://your-saleor-api-url.com/graphql/"
    NEXT_PUBLIC_STOREFRONT_URL: "https://your-storefront-url.com"
    SALEOR_APP_TOKEN: "your-saleor-app-token"
    NEXT_PUBLIC_URL: "https://your-public-url.com"
    NEXT_SECRET_NEWSLETTER_ENDPOINT: "https://your-newsletter-endpoint.com"
    NEXT_SALEOR_TOKEN: "your-saleor-token"
    NEXT_PUBLIC_SALEOR_TOKEN: "your-public-saleor-token"
    NEXT_PUBLIC_CHANNEL_ID: "your-channel-id"
    NEXT_PUBLIC_ALGOLIA_APP_ID: "your-algolia-app-id"
    NEXT_PUBLIC_ALGOLIA_API_KEY: "your-algolia-api-key"
    NEXT_PUBLIC_ALGOLIA_INDEX_NAME: "your-algolia-index-name"

redis:
  image:
    repository: library/redis
    tag: "7.0-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 6379
  persistence:
    enabled: true
    size: 1Gi
  resources: {}

jaeger:
  image:
    repository: jaegertracing/all-in-one
    tag: latest
    pullPolicy: IfNotPresent
  service:
    ports:
      - name: udp-5775
        port: 5775
        protocol: UDP
      - name: udp-6831
        port: 6831
        protocol: UDP
      - name: udp-6832
        port: 6832
        protocol: UDP
      - name: tcp-5778
        port: 5778
      - name: tcp-16686
        port: 16686
      - name: tcp-14268
        port: 14268
      - name: tcp-9411
        port: 9411
  resources: {}

mailpit:
  image:
    repository: axllent/mailpit
    tag: latest
    pullPolicy: IfNotPresent
  service:
    smtpPort: 1025
    webPort: 8025
  resources: {}

persistence:
  media:
    enabled: true
    storageClass: standard
    size: 1Gi
  gcs:
    enabled: true
    secretName: gcs-credentials