replicaCount: 1

images:
  api: ghcr.io/saleor/saleor:3.20
  dashboard: ghcr.io/saleor/saleor-dashboard:latest
  redis: library/redis:7.0-alpine
  worker: ghcr.io/saleor/saleor:3.20
  jaeger: jaegertracing/all-in-one
  mailpit: axllent/mailpit

components:
  api:
    enabled: true
    service:
      port: 8000
      type: ClusterIP
    extraParams: {}
  dashboard:
    enabled: true
    service:
      port: 9000
      type: ClusterIP
    extraParams: {}
  postgresql:
    enabled: true
    auth:
      username: saleor
      password: saleor
    persistence:
      enabled: true
      size: 5Gi
    extraParams: {}
  redis:
    enabled: true
    service:
      port: 6379
      type: ClusterIP
    master:
      persistence:
        enabled: true
        size: 2Gi
    replica:
      replicaCount: 0  # Встановіть 0, якщо не потрібні репліки
      persistence:
        enabled: true
        size: 2Gi
    extraParams: {}
  jaeger:
    enabled: true
    service:
      ports:
        - 5775
        - 6831
        - 6832
        - 5778
        - 16686
        - 14268
        - 9411
      type: ClusterIP
    extraParams: {}
  mailpit:
    enabled: true
    service:
      smtpPort: 1025
      webPort: 8025
      type: ClusterIP
    extraParams: {}

volumes:
  saleorDb: /var/lib/postgresql/data
  saleorRedis: /data
  saleorMedia: /app/media