apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "saleor.fullname" . }}-media
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # GCP's Regional storage class for ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.media.size }}