apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saleor.fullname" . }}-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "saleor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "saleor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "saleor.fullname" . }}-postgresql/{{ .Values.postgresql.auth.database }}
            - name: REDIS_URL
              value: redis://{{ include "saleor.fullname" . }}-redis-master:6379/0
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "saleor.fullname" . }}-secret
                  key: secret-key
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}