apiVersion: v1
kind: Service
metadata:
  name: {{ include "saleor.fullname" . }}-headless
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  clusterIP: None # Робить сервіс headless
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "saleor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api