apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: saleor
spec:
  type: {{ .Values.components.api.service.type }}
  ports:
    - port: {{ .Values.components.api.service.port }}
      targetPort: {{ .Values.components.api.service.port }}
  selector:
    app: saleor
    component: api