apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saleor.fullname" . }}-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "saleor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "saleor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: JAEGER_AGENT_HOST
              value: jaeger
            - name: DASHBOARD_URL
              value: http://localhost:9000/
            - name: ALLOWED_HOSTS
              value: localhost,api
          volumeMounts:
            - name: saleor-media
              mountPath: /app/media
      volumes:
        - name: saleor-media
          persistentVolumeClaim:
            claimName: saleor-media