apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: saleor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: saleor
      component: api
  template:
    metadata:
      labels:
        app: saleor
        component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.images.api }}"
          ports:
            - containerPort: {{ .Values.services.api.port }}
          env:
            - name: JAEGER_AGENT_HOST
              value: "{{ .Values.env.api.JAEGER_AGENT_HOST }}"
            - name: DASHBOARD_URL
              value: "{{ .Values.env.api.DASHBOARD_URL }}"
            - name: ALLOWED_HOSTS
              value: "{{ .Values.env.api.ALLOWED_HOSTS }}"
          {{- with .Values.components.api.extraParams }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
            - name: saleor-media
              mountPath: {{ .Values.volumes.saleorMedia }}
      volumes:
        - name: saleor-media
          persistentVolumeClaim:
            claimName: saleor-media