apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saleor.fullname" . }}-api
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "saleor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "saleor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      imagePullSecrets:
        - name: ghcr-secret 
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "saleor.fullname" . }}-config
            - secretRef:
                name: {{ include "saleor.fullname" . }}-secret
          volumeMounts:
            - name: media
              mountPath: /app/media
            - name: gcs-credentials
              mountPath: /etc/secrets
              readOnly: true
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "saleor.fullname" . }}-media
        - name: gcs-credentials
          secret:
            secretName: {{ .Values.persistence.gcs.secretName }}