apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "saleor.fullname" . }}-config
data:
  DEFAULT_CHANNEL_SLUG: {{ .Values.global.env.DEFAULT_CHANNEL_SLUG | quote }}
  HTTP_IP_FILTER_ALLOW_LOOPBACK_IPS: {{ .Values.global.env.HTTP_IP_FILTER_ALLOW_LOOPBACK_IPS | quote }}
  HTTP_IP_FILTER_ENABLED: {{ .Values.global.env.HTTP_IP_FILTER_ENABLED | quote }}
  CELERY_BROKER_URL: {{ .Values.global.env.CELERY_BROKER_URL | quote }}
  DATABASE_URL: {{ .Values.global.env.DATABASE_URL | quote }}  # Add DATABASE_URL
  DEFAULT_FROM_EMAIL: {{ .Values.global.env.DEFAULT_FROM_EMAIL | quote }}
  EMAIL_URL: {{ .Values.global.env.EMAIL_URL | quote }}
  JAEGER_AGENT_HOST: {{ .Values.global.env.JAEGER_AGENT_HOST | quote }}
  DASHBOARD_URL: {{ .Values.global.env.DASHBOARD_URL | quote }}
  ALLOWED_HOSTS: {{ .Values.global.env.ALLOWED_HOSTS | quote }}
  API_URL: {{ .Values.global.env.API_URL | quote }}
  STATIC_URL: {{ .Values.global.env.STATIC_URL | quote }}

  # GCS Specific Settings
  DEFAULT_FILE_STORAGE: {{ .Values.global.env.DEFAULT_FILE_STORAGE | quote }}
  PRIVATE_FILE_STORAGE: {{ .Values.global.env.PRIVATE_FILE_STORAGE | quote }}
  GS_CREDENTIALS_FILE_PATH: {{ .Values.global.env.GS_CREDENTIALS_FILE_PATH | quote }}
  GS_BUCKET_NAME: {{ .Values.global.env.GS_BUCKET_NAME | quote }}
  MEDIA_URL: {{ .Values.global.env.MEDIA_URL | quote }}
  GS_PROJECT_ID: {{ .Values.global.env.GS_PROJECT_ID | quote }}
  GS_LOCATION: {{ .Values.global.env.GS_LOCATION | quote }}
  GS_CUSTOM_ENDPOINT: {{ .Values.global.env.GS_CUSTOM_ENDPOINT | quote }}
  GS_MEDIA_BUCKET_NAME: {{ .Values.global.env.GS_MEDIA_BUCKET_NAME | quote }}
  GS_AUTO_CREATE_BUCKET: {{ .Values.global.env.GS_AUTO_CREATE_BUCKET | quote }}
  GS_QUERYSTRING_AUTH: {{ .Values.global.env.GS_QUERYSTRING_AUTH | quote }}
  GS_DEFAULT_ACL: {{ .Values.global.env.GS_DEFAULT_ACL | quote }}
  GS_MEDIA_CUSTOM_ENDPOINT: {{ .Values.global.env.GS_MEDIA_CUSTOM_ENDPOINT | quote }}
  GS_EXPIRATION: {{ .Values.global.env.GS_EXPIRATION | quote }}
  GS_FILE_OVERWRITE: {{ .Values.global.env.GS_FILE_OVERWRITE | quote }}
  GOOGLE_APPLICATION_CREDENTIALS: {{ .Values.global.env.GOOGLE_APPLICATION_CREDENTIALS | quote }}
  STATIC_ROOT: {{ .Values.global.env.STATIC_ROOT | quote }}
  MEDIA_ROOT: {{ .Values.global.env.MEDIA_ROOT | quote }}
  SALEOR_DOMAIN: {{ .Values.global.env.SALEOR_DOMAIN | quote }}
  ALLOWED_CLIENT_HOSTS: {{ .Values.global.env.ALLOWED_CLIENT_HOSTS | quote }}