apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: saleor
spec:
  type: {{ .Values.services.db.type }}
  ports:
    - port: {{ .Values.services.db.port }}
      targetPort: {{ .Values.services.db.port }}
  selector:
    app: saleor
    component: db