apiVersion: v1
kind: Service
metadata:
  name: {{ include "saleor.fullname" . }}-jaeger
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
    app.kubernetes.io/component: jaeger
spec:
  ports:
    {{- range .Values.jaeger.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "saleor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jaeger