apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mailpit
  labels:
    app: saleor
spec:
  type: {{ .Values.services.mailpit.type }}
  ports:
    - name: smtp
      port: {{ .Values.services.mailpit.smtpPort }}
      targetPort: {{ .Values.services.mailpit.smtpPort }}
    - name: web
      port: {{ .Values.services.mailpit.webPort }}
      targetPort: {{ .Values.services.mailpit.webPort }}
  selector:
    app: saleor
    component: mailpit