apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saleor.fullname" . }}-mailpit
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
    app.kubernetes.io/component: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "saleor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mailpit
  template:
    metadata:
      labels:
        {{- include "saleor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mailpit
    spec:
      containers:
        - name: mailpit
          image: "{{ .Values.mailpit.image.repository }}:{{ .Values.mailpit.image.tag }}"
          imagePullPolicy: {{ .Values.mailpit.image.pullPolicy }}
          ports:
            - containerPort: 1025
              name: smtp
            - containerPort: 8025
              name: web
          {{- with .Values.mailpit.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}