apiVersion: v1
kind: Service
metadata:
  name: {{ include "saleor.fullname" . }}-mailpit
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
    app.kubernetes.io/component: mailpit
spec:
  ports:
    - port: {{ .Values.mailpit.service.smtpPort }}
      targetPort: 1025
      protocol: TCP
      name: smtp
    - port: {{ .Values.mailpit.service.webPort }}
      targetPort: 8025
      protocol: TCP
      name: web
  selector:
    {{- include "saleor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mailpit