apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: saleor
spec:
  type: {{ .Values.services.redis.type }}
  ports:
    - port: {{ .Values.services.redis.port }}
      targetPort: {{ .Values.services.redis.port }}
  selector:
    app: saleor
    component: redis