apiVersion: v1
kind: Service
metadata:
  name: {{ include "saleor.fullname" . }}-redis
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "saleor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis