apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "saleor.fullname" . }}-worker
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "saleor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "saleor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: ["celery", "-A", "saleor", "--app=saleor.celeryconf:app", "worker", "--loglevel=info", "-B"]
          envFrom:
            - configMapRef:
                name: {{ include "saleor.fullname" . }}-config
            - secretRef:
                name: {{ include "saleor.fullname" . }}-secret
          volumeMounts:
            - name: media
              mountPath: /app/media
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: media
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi