apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: saleor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor
      component: worker
  template:
    metadata:
      labels:
        app: saleor
        component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.images.worker }}"
          command: ["celery", "-A", "saleor", "--app=saleor.celeryconf:app", "worker", "--loglevel=info", "-B"]
          envFrom:
            - secretRef:
                name: backend-env