apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saleor.fullname" . }}-api
  labels:
    {{- include "saleor.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "saleor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "saleor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "saleor.fullname" . }}-media
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: media
              mountPath: /app/media
          envFrom:
            - configMapRef:
                name: {{ include "saleor.fullname" . }}-api-config
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}