name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add dependency repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Update Helm dependencies
        run: |
          helm dependency update .

      # Крок 1: Створення пакету
      - name: Package Helm chart
        run: |
          mkdir -p .cr-release-packages
          helm package . -d .cr-release-packages

      # Крок 2: Зберігаємо пакет як артефакт
      - name: Save package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: helm-charts
          path: .cr-release-packages/*.tgz
          retention-days: 1

      # Крок 3: Створення GitHub Release
      - name: Create Release
        run: |
          version=$(grep '^version:' Chart.yaml | sed 's/[^0-9.]*//g' | tr -d '[:space:]')
          if [ -n "$version" ]; then
            if ! gh release view "v$version" &>/dev/null; then
              gh release create "v$version" .cr-release-packages/*.tgz \
                --title "Release v$version" \
                --generate-notes
            else
              echo "Release v$version already exists"
            fi
          else
            echo "Error: Could not determine version from Chart.yaml"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Крок 4: Переключення на gh-pages
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          clean: true

      # Крок 5: Відновлення пакету з артефакту
      - name: Download chart artifact
        uses: actions/download-artifact@v3
        with:
          name: helm-charts
          path: .

      # Крок 6: Оновлення індексу
      - name: Update Helm index
        run: |
          if [ -f index.yaml ]; then
            helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }} --merge index.yaml
          else
            helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          fi

      # Крок 7: Публікація змін
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update Helm chart release" || echo "No changes to commit"
          git push origin gh-pages