name: Release Charts
on:
  push:
    branches:
      - main
jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Add dependency repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Update Helm dependencies
        run: |
          helm dependency update .
      - name: Package Helm chart
        run: |
          mkdir -p .cr-release-packages
          helm package . -d .cr-release-packages
          ls -la .cr-release-packages/
      - name: Debug Current Directory
        run: |
          echo "Debugging current directory after helm package:"
          pwd
          ls -la
      - name: Save package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: helm-charts
          path: ./.cr-release-packages/**  # Виправлення шляху для збереження
  publish:
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          clean: true
      - name: List artifacts
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts"
      - name: Download chart artifact
        uses: actions/download-artifact@v3
        with:
          name: helm-charts
          path: ./
      - name: List downloaded files
        run: |
          echo "Files after downloading artifact:"
          ls -la
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Update Helm index
        run: |
          if [ -f index.yaml ]; then
            helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }} --merge index.yaml
          else
            helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          fi
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update Helm chart release" || echo "No changes to commit"
          git push origin gh-pages